version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'admin'
    ports:
      - 5432:5432
    volumes: 
      - ./sql/table_gen.sql:/docker-entrypoint-initdb.d/table_gen.sql